Update npm audit fix.yml

diff --git a/.github/workflows/npm audit fix.yml b/.github/workflows/npm audit fix.yml
--- a/.github/workflows/npm audit fix.yml
+++ b/.github/workflows/npm audit fix.yml
@@ -23,7 +23,7 @@ jobs:
       run: npm ci
 
     - name: Run npm audit fix
-      run: npm audit fix
+      run: npm audit fix || echo "Some vulnerabilities could not be fixed."
 
     - name: Commit changes
       run: |
